### ISSUE TITLE
重要度・期限次第で、タスクコンポーネントのデザインを切り換える

### ISSUE THREAD

**Issue by ryutaro-kimura** [scla-sagauniv/megusuri-no-hako#6]
- タスク作成時の重要度次第で、デザインを切り換えるようにする
  - CSS?背景画像が楽か？
- ハンバーグ = 重要度大
- チーズ = 重要度中
- レタス = 重要度小

**Comment by ryutaro-kimura** [comment]
- タスク作成時の期限が過ぎるかどうか次第で、デザインを切り換えるようにする
- 新鮮 = 期限内
- 腐敗 = 期限過ぎた

**Comment by yunatoma** [comment]
重要度
- [x] ①最重要(高級トマト)
    - 赤色 
- [x] ②高(肉)
    - 茶色
- [x] ③普通(チーズ)
    - 黄色
- [x] ④低(レタス)
    - 緑
